### GraphQL Playground

### Query

POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "{ lesson(id: \"cec57d7d-863f-4e98-a585-238749bac7c3\") { name startDate } }"
}

# query {
#   lesson(id: "cec57d7d-863f-4e98-a585-238749bac7c3") {
#     name
#   }
# }


# {
#   "query": "{ lesson { name startDate } }"
# }

# query {
#   lesson {
#     name
#   }
# }

# query {
#   lessons {
#     name
#   }
# }

# query {
#   students {
#     firstName
#   }
# }

# query {
#   student(id: "e1b4e577-c8c9-4c56-8c7e-05bbe33f7355") {
#     firstName
#   }
# }

### Mutation

POST http://localhost:3000/graphql
Content-Type: application/json

{
  "mutation": "{ createLesson(name: \"Physics Class\", startDate: \"2020-03-28T18:00:00Z\", endDate: \"2020-03-28T18:30:00Z\") { name } }"
}

# mutation {
#   createLesson(
#     name: "Physics Class",
#     startDate: "2020-03-28T18:00:00Z",
#     endDate: "2020-03-28T18:30:00Z"
#   ) {
#     name
#   }
# }


# mutation {
#   createLesson(
#     createLessonInput: {
#       name: "NestJ2",
#       startDate: "2020-03-28T19:00:00Z",
#       endDate: "2020-03-28T19:30:00Z"
#     }
#   ) {
#     id
#     name
#   }
# }


# mutation {
#   createStudent(createStudentInput: {
#     firstName: "John",
#     lastName: "Doe"
#   }) {
#     id
#     firstName
#   }
# }

# mutation {
#   assignStudentsToLesson(assignStudentsToLessonInput: {
#     lessonId: "3e4c25ee-f879-43f8-896d-4930f3ab04ef"
#     studentIds: [
#       "e1b4e577-c8c9-4c56-8c7e-05bbe33f7355",
#       "b6836795-2238-4ff2-a682-8a378743bf28",
#       "568dbaa7-6170-4a1a-921d-6f72fa779125"
#     ]
#   }) {
#     name
#   }
# }
